### ISSUE TITLE
Role assigning through Selects

### ISSUE THREAD

**Issue by Glazelf** [Glazelf/NinigiBot#121]
- [x] Implement basic select interactions
- [x] Convert code to workable selects
- [x] Catch to old method if role count >25

**Comment by Glazelf** [comment]
Acceptable level of functionality in 5ce3275adcab76ccb7764241b965a34d1e3b2092.
Some bugs might exist.

**Comment by bettydreemurr** [comment]
⭐ masterclass ⭐
