### ISSUE TITLE
equipment.toString() should not return a promise

### ISSUE THREAD

**Issue by villa7** [Glazelf/NinigiBot#194]
Shop equipment command outputs unresolved promises instead of equipment descriptions

**To Reproduce**
use command: `?shop equipment`

**Expected behavior**
outputs the list of equipments

**Screenshots**
![image](https://user-images.githubusercontent.com/1696813/136116313-c92c4143-5e18-486a-8e9f-a4d3fe5f3cd2.png)

**Additional context**
[`equipment.toString()`](https://github.com/Glazelf/NinigiBot/blob/e47b36f3c3e4f97775546fdab4da3d46b5adf7c3/database/dbObjects.js#L59) is async and the only async function in it is [`parseInteger`](https://github.com/Glazelf/NinigiBot/blob/master/util/parseInteger.js) which is also async for some reason

**Comment by Glazelf** [comment]
Interesting bug, looking into it. I have no idea what the difference from `food` is that would cause this behaviour. Buying equipment still works properly, it's just displaying it in the shop.
I removed some unnecessary awaits in c35d90a6b2e32beddb6a2fc17415a669f07cdf29.
![DiscordCanary_JJmTPe9nef](https://user-images.githubusercontent.com/35176230/136145380-dac325bf-dcc7-4b46-b22f-326b92368b7b.png)

**Comment by Glazelf** [comment]
Fixed in 736b9283df14db982c0cf8f636e4422555ed3e86.
