### ISSUE TITLE
Suggestions

### ISSUE THREAD

**Issue by Glazelf** [Glazelf/NinigiBot#63]
Mainly for  suggestions for Shinx text strings, gifs and other randomized text returns that don't warrant an entire issue on their own.

![](https://i.imgur.com/VYFtEhh.png)
Comment your suggested quote and a number matching your suggested reaction

**Comment by AtwerJ** [comment]
Shinx got voted off even though he did medbay scan. (angry Shinx)
Shinx is confused as to how the 3rd tribute died in the Yoomking story. (worried Shinx)

**Comment by Glazelf** [comment]
https://github.com/Glazelf/NinigiBot/issues/63#issuecomment-687655020

**Comment by Glazelf** [comment]
https://github.com/Glazelf/NinigiBot/issues/63#issuecomment-687655020

> Shinx got voted off even though he did medbay scan. (angry Shinx)
> Shinx is confused as to how the 3rd tribute died in the Yoomking story. (worried Shinx)
https://github.com/Glazelf/NinigiBot/issues/63#issuecomment-687655020
Added.

**Comment by Glazelf** [comment]
Moved to #77

**Comment by Glazelf** [comment]
Moved to #77
