### ISSUE TITLE
Allow changing default ephemeral value to false

### ISSUE THREAD

**Issue by kkellogg378** [Glazelf/NinigiBot#742]
**Is your feature request related to a problem? Please describe.**
No

**Describe the solution you'd like**
A command or setting to set the ephemeral value to false by default instead of true

**Describe alternatives you've considered**
n/a

**Additional context**
n/a

**Comment by Glazelf** [comment]
Would this be on a per-user basis? 
And would this command change the default for every command or per command?
I can add this, but it might have a significant impact on the database if you can toggle ephemeral defaults per command per user so I would probably prefer having it apply to all commands for a specific user.

**Comment by Glazelf** [comment]
Added support for this between cf2ebdc8a7e709148bd6cc03f7df7085981703c6, 1f5867e0a8c99a46dd939ad398a12a23fe11b740 and 7b5255cd7427d3dd543ca1b54f7d942ef4cf0373.

Please use `/usersettings ephemeraldefault` to change your personal default.

Thanks for the suggestion and I'm glad you're enjoying our bot!
