### ISSUE TITLE
One boot file

### ISSUE THREAD

**Issue by Glazelf** [Glazelf/NinigiBot#843]
Combine `forever.js`, `bot.js` and `index.js` into one file.
Currently there are 2 parameters, `forever` and `sharding`. 
`forever.js` boots with `forever`, `index.js` boots with `sharding`, `bot.js` boots with neither.

To cover every combination we would need a fourth file to boot with both parameters.
Instead all three should be combined into one file with boolean variables initialized near the top of the file so users can determine for themselves what they want.

**Comment by Glazelf** [comment]
Might also want to do some bugfixing with sharding in general while looking into this anyways.

**Comment by dali2g** [comment]
Hey , I'm tryna fix this out
